#
# Nmake File For MS Visual C/C++
# Use 'nmake -f Makefile.win'

NODEBUG=1

INCS = /I.
LIB = libezxml.lib
DLL = libezxml.dll

OBJS = ezxml.obj

all: lib

lib: $(OBJS)
	link.exe /lib /nologo /out:$(LIB) $(OBJS)

dll: $(OBJS)
	link.exe /dll /nologo /out:$(DLL) $(OBJS)

.c.obj:
	$(CC) /nologo $(CFLAGS) $(INCS) /c $<

# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~ $(LIB) $(DLL)
