#
# Nmake file - Windows version
# Use 'nmake -f Makefile.win'

NODEBUG=1

INCS = /I..\libslink /I..\ezxml
OPTS = -D_CRT_SECURE_NO_WARNINGS
LIBS = ..\libslink\libslink.lib ..\ezxml\libezxml.lib ws2_32.lib

BIN = ..\slinktool.exe

OBJS = archive.obj dsarchive.obj slinkxml.obj slinktool.obj

all: $(BIN)

$(BIN):	$(OBJS)
	link.exe /nologo /out:$(BIN) $(LIBS) $(OBJS)

.c.obj:
	$(CC) /nologo $(CFLAGS) $(INCS) $(OPTS) /c $<

# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~ $(BIN)
